name: derekloe
favicon: null
layout_spectrum: 0.7255343119613826
typography_spectrum: 0.35879315505735576
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#b4b9bd'
    - '#4b124d'
    - '#0000ff'
    - '#ff00ff'
  brandStrength: 0.0013305265456438065
  lightness: 0.033809134969487786
  saturation: 0.3822372150607407
  rhythmicContrast: 0.6642735572531819
purpose: []
