name: derekloe
favicon: null
layout_spectrum: 1
typography_spectrum: 0.90608
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#b4b9bd'
    - '#4b124d'
    - '#0000ff'
    - '#ff00ff'
  brandStrength: 0
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
