typography_spectrum: 0.90608
color:
  brandColors:
    - '#fefefe'
    - '#b4b9bd'
    - '#4b124d'
    - '#0000ff'
    - '#ff00ff'
  brandStrength: 0
  lightness: 0
  saturation: 0.3125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: derekloe
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: ce177640-89bd-4e7b-904a-16ba7462bdc6
    url: 2016-03-29-the-world-is-so-technical-nowadays-people-only-see-color.html
    name: Check
    type: content
  - id: edf701e9-5ff8-45e8-9343-269f8e70deb1
    url: 2016-07-21-hudson-nights-or-wisconsin.html
    name: Films
    type: content
favicon: null
purpose: []
